#!/usr/bin/env php
<?php

use Px2svg\Converter;

$path = dirname(__DIR__);

require $path.'/vendor/autoload.php';

try {
    if (count($argv) < 1) {
        throw new InvalidArgumentException('Too few arguments passed to converter');
    }
    header('Content-Type: image/svg+xml');
    echo (new Converter())->loadImage($argv[1])->generateSVG();
} catch (Exception $e) {
    echo $e->getMessage();
    readfile('help.txt');
    die(1);
}
